typography_spectrum: 0.7035944804083556
color:
  brandStrength: 0.7914254632778466
  lightness: 0.35830337670631707
  saturation: 0.21574641740880907
  rhythmicContrast: 0.9632321030367166
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.705871079582721
name: Jason Curtis
title: Producer
